name: Build the game Windows & MaxOsX 🎮

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  init-data:
    name: Set the workflow data 📊
    runs-on: ubuntu-latest
    steps:
      - name: Get the number of the current build
        id: builder_number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  buildWindows:
    name: Build the game for Windows 🪟
    runs-on: ubuntu-latest
    needs: init-data
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the code 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get Unity Cache 🗄️
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Build Unity Project for Windows 🪟
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.42f1
          allowDirtyBuild: true

      - name: Upload the build 📤
        uses: actions/upload-artifact@v3
        with:
          name: build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}
          path: build/StandaloneWindows64

      - name: Zip the build 📦
        uses: montudor/action-zip@v1
        with:
          args: zip qq -r build/build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip build/StandaloneWindows64

  buildMacOs:
    name: Build the game for MacOsX 🍏
    runs-on: macos-latest
    needs: init-data
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the code 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get Unity Cache 🗄️
        uses: actions/cache@v4
        with:
            path: Library
            key: Library-${{ matrix.targetPlatform }}
            restore-keys: Library-

      - name: Build Unity Project for MacOsX 🍏
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          unityVersion: 2022.3.42f1
          allowDirtyBuild: true

      - name: Upload the build 📤
        uses: actions/upload-artifact@v3
        with:
          name: build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}
          path: build/StandaloneOSX

      - name: Zip the build 📦
        uses: montudor/action-zip@v1
        with:
          args: zip qq -r build/build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip build/StandaloneOSX

  publishAsRelease:
    name: Publish the build as a release 🚀
    runs-on: ubuntu-latest
    needs: [buildWindows, buildMacOs]
    steps:
      - name: Create a release 📦
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.init-data.outputs.builder_number }}
          release_name: Release ${{ needs.init-data.outputs.builder_number }}
          draft: false
          prerelease: false

      - name: Upload Windows build 🪟
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip
          asset_name: build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip
          asset_content_type: application/zip

      - name: Upload MacOs build 🍏
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip
          asset_name: build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip
          asset_content_type: application/zip

      - name: Publish the release 🚀
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ needs.init-data.outputs.builder_number }}
          release_name: Release ${{ needs.init-data.outputs.builder_number }}
          draft: false
          prerelease: false
          body: |
            This is the release of the game.
            You can download the game for Windows and MacOsX.
            Enjoy! 🎮